{"sections":[],"kind":"symbol","topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/AnalyticOrder","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Builder","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Candle","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleExchange","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandlePeriod","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandlePriceLevel","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleSymbol","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXAuthToken","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXDateOffset","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXEndpoint","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXFeed","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXFeedSubscription","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXFeedTimeSeriesSubscription","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXInstrumentProfileCollector","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXInstrumentProfileConnection","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXInstrumentProfileReader","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXProfileIterator","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXPublisher","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXSchedule","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXTimeFormat","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXTimeZone","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/GenericIndexedEventSubscriptionSymbol","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Greeks","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IcebergTypeExt","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IndexedEventSource","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IndexedEventSubscriptionSymbol","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/InstrumentProfile","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/MarketDepthModel","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/MarketEvent","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/MarketEventSymbols","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/NativeInstrumentProfileCollector","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OnDemandService","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OptionChain","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OptionChainsBuilder","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OptionSale","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OptionSeries","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Order","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OrderBase","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OrderBook","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OrderSource","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OtcMarketsOrder","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Profile","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/QdsUtils","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Quote","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ScheduleDay","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ScheduleSession","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ScopeExt","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Series","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/SnapshotProcessor","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/SpreadOrder","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/StringUtil","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Summary","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/SymbolParser","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/SystemProperty","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TheoPrice","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TimeAndSale","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TimeSeriesSubscriptionSymbol","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TimeUtil","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Trade","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TradeBase","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TradeETH","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Underlying","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/WildcardSymbol"]},{"title":"Protocols","identifiers":["doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXEndpointListener","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXEventListener","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXInstrumentProfileConnectionListener","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXInstrumentProfileUpdateListener","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ICandleSymbolProperty","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IEventType","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IIndexedEvent","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ILastingEvent","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IObservableSubscription","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ITimeSeriesEvent","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/MarketDepthListener","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ObservableSubscriptionChangeListener","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ScopingFunctionSupported","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/SnapshotDelegate","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Symbol"]},{"title":"Structures","identifiers":["doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXCandleAlignment","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXCandlePrice","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXCandleSession","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXCandleType","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXOtcMarketsPriceType","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXPriceType","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/MarketEventConst"]},{"title":"Functions","identifiers":["doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/stringReference(_:)"]},{"identifiers":["doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Long","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Role"],"title":"Type Aliases"},{"title":"Enumerations","identifiers":["doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ArgumentException","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleAlignment","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandlePrice","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleSession","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleType","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXEndpointState","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXInstrumentProfileConnectionState","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DayFilter","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Direction","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/EventCode","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/GraalException","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IcebergType","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/InstrumentProfileField","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/InstrumentProfileType","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OrderAction","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OtcMarketsPriceType","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/PriceType","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ScheduleSessionType","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Scope","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/SessionFilter","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ShortSaleRestriction","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Side","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TimeAndSaleType","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TradingStatus","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TxMode"]},{"identifiers":["doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Foundation","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Swift"],"title":"Extended Modules"}],"variants":[{"paths":["\/documentation\/dxfeedframework"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dxfeedframework"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"module","title":"DXFeedFramework","modules":[{"name":"DXFeedFramework"}],"role":"collection","roleHeading":"Framework","externalID":"DXFeedFramework"},"hierarchy":{"paths":[[]]},"identifier":{"url":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework","interfaceLanguage":"swift"},"references":{"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/OtcMarketsPriceType":{"type":"topic","url":"\/documentation\/dxfeedframework\/otcmarketspricetype","role":"symbol","title":"OtcMarketsPriceType","kind":"symbol","abstract":[{"text":"Type of prices on the OTC Markets.","type":"text"}],"navigatorTitle":[{"text":"OtcMarketsPriceType","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OtcMarketsPriceType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OtcMarketsPriceType","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXCandleSession":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxcandlesession","role":"symbol","title":"DXCandleSession","kind":"symbol","abstract":[{"type":"text","text":"This "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXCandleSession"},{"type":"text","text":" structure is created to circumvent the limitation that enums in Swift cannot contain stored properties."},{"type":"text","text":" "},{"type":"text","text":"The “Enums must not contain stored properties” error occurs when attempting to add a stored property to an enum. Instead, we use this structure to store data that we would like to include in the enum."}],"navigatorTitle":[{"text":"DXCandleSession","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXCandleSession","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DXCandleSession","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Side":{"kind":"symbol","title":"Side","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Side","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Side","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"Side","kind":"identifier"}],"abstract":[{"type":"text","text":"Side of an order or a trade."}],"url":"\/documentation\/dxfeedframework\/side"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXInstrumentProfileConnectionState":{"url":"\/documentation\/dxfeedframework\/dxinstrumentprofileconnectionstate","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DXInstrumentProfileConnectionState","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DXInstrumentProfileConnectionState","kind":"identifier"}],"title":"DXInstrumentProfileConnectionState","abstract":[{"text":"Instrument profile connection state.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXInstrumentProfileConnectionState"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/ObservableSubscriptionChangeListener":{"type":"topic","url":"\/documentation\/dxfeedframework\/observablesubscriptionchangelistener","role":"symbol","title":"ObservableSubscriptionChangeListener","kind":"symbol","abstract":[{"type":"text","text":"The listener interface for receiving notifications on the changes of observed subscription."},{"text":" ","type":"text"},{"type":"text","text":"All methods on this interface are invoked while holding a lock on "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IObservableSubscription"},{"type":"text","text":" instance,"},{"type":"text","text":" "},{"type":"text","text":"thus all changes for a given subscription are synchronized with respect to each other."}],"navigatorTitle":[{"text":"ObservableSubscriptionChangeListener","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ObservableSubscriptionChangeListener","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ObservableSubscriptionChangeListener"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXEndpointListener":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxendpointlistener","role":"symbol","title":"DXEndpointListener","kind":"symbol","abstract":[{"type":"text","text":"Notifies a change in the state of this endpoint."}],"navigatorTitle":[{"text":"DXEndpointListener","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXEndpointListener","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DXEndpointListener","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/OrderAction":{"type":"topic","url":"\/documentation\/dxfeedframework\/orderaction","abstract":[],"title":"OrderAction","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OrderAction","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"OrderAction","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"OrderAction","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/OnDemandService":{"navigatorTitle":[{"text":"OnDemandService","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OnDemandService"}],"kind":"symbol","abstract":[{"text":"Provides on-demand historical tick data replay controls.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This class is used to seamlessly transition from ordinary real-time or delayed data feed to the"},{"text":" ","type":"text"},{"text":"replay of the tick-by-tick history of market data behaviour without any changes to the code","type":"text"},{"type":"text","text":" "},{"type":"text","text":"that consumes and process these market events."}],"url":"\/documentation\/dxfeedframework\/ondemandservice","role":"symbol","type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OnDemandService","title":"OnDemandService"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXInstrumentProfileConnection":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxinstrumentprofileconnection","role":"symbol","title":"DXInstrumentProfileConnection","kind":"symbol","abstract":[{"text":"Connects to an instrument profile URL and reads instrument profiles with support of","type":"text"},{"type":"text","text":" "},{"type":"text","text":"streaming live updates."}],"navigatorTitle":[{"kind":"identifier","text":"DXInstrumentProfileConnection"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXInstrumentProfileConnection","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DXInstrumentProfileConnection"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/IEventType":{"abstract":[{"type":"text","text":"Marks all event types that can be received via dxFeed API."}],"navigatorTitle":[{"text":"IEventType","kind":"identifier"}],"title":"IEventType","url":"\/documentation\/dxfeedframework\/ieventtype","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IEventType"}],"kind":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IEventType"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXCandlePrice":{"url":"\/documentation\/dxfeedframework\/dxcandleprice","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DXCandlePrice","kind":"identifier"}],"abstract":[{"text":"This ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXCandlePrice"},{"type":"text","text":" structure is created to circumvent the limitation that enums in Swift cannot contain stored properties."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DXCandlePrice","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXCandlePrice","title":"DXCandlePrice"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/SystemProperty":{"type":"topic","url":"\/documentation\/dxfeedframework\/systemproperty","role":"symbol","title":"SystemProperty","kind":"symbol","abstract":[{"type":"text","text":"Wrapper over the Java java.lang.System class, contains work with property getter\/setter methods."}],"navigatorTitle":[{"kind":"identifier","text":"SystemProperty"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/SystemProperty","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SystemProperty"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/ArgumentException":{"type":"topic","abstract":[{"text":"Represents errors that occur when candle manipulations","type":"text"}],"url":"\/documentation\/dxfeedframework\/argumentexception","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ArgumentException","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ArgumentException"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ArgumentException"}],"title":"ArgumentException","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/OtcMarketsOrder":{"role":"symbol","url":"\/documentation\/dxfeedframework\/otcmarketsorder","type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OtcMarketsOrder","title":"OtcMarketsOrder","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OtcMarketsOrder"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"OtcMarketsOrder"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/ICandleSymbolProperty":{"role":"symbol","kind":"symbol","abstract":[{"text":"Property of the ","type":"text"},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleSymbol","type":"reference","isActive":true}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ICandleSymbolProperty"}],"navigatorTitle":[{"text":"ICandleSymbolProperty","kind":"identifier"}],"title":"ICandleSymbolProperty","type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ICandleSymbolProperty","url":"\/documentation\/dxfeedframework\/icandlesymbolproperty"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXAuthToken":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxauthtoken","role":"symbol","title":"DXAuthToken","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXAuthToken","type":"reference","isActive":true},{"text":" class represents an authorization token and encapsulates information about the authorization","type":"text"},{"type":"text","text":" "},{"text":"scheme and its associated value.","type":"text"}],"navigatorTitle":[{"text":"DXAuthToken","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXAuthToken","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DXAuthToken"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/OptionSale":{"title":"OptionSale","abstract":[{"type":"text","text":"Option Sale event represents a trade or another market event with the price"},{"text":" ","type":"text"},{"text":"(for example, market open\/close price, etc.) for each option symbol listed under the specified Underlying.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OptionSale","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OptionSale","kind":"identifier"}],"navigatorTitle":[{"text":"OptionSale","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/optionsale"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/AnalyticOrder/icebergHiddenSize":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"icebergHiddenSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/dxfeedframework\/analyticorder\/iceberghiddensize","abstract":[{"text":"Gets or sets iceberg hidden size of this analytic order.","type":"text"}],"title":"icebergHiddenSize","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/AnalyticOrder\/icebergHiddenSize","kind":"symbol","type":"topic","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/AnalyticOrder/icebergExecutedSize":{"abstract":[{"text":"Gets or sets iceberg executed size of this analytic order.","type":"text"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/AnalyticOrder\/icebergExecutedSize","kind":"symbol","url":"\/documentation\/dxfeedframework\/analyticorder\/icebergexecutedsize","title":"icebergExecutedSize","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"icebergExecutedSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/OrderSource":{"abstract":[{"text":"Identifies source of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Order"},{"type":"text","text":", "},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/AnalyticOrder","isActive":true,"type":"reference"},{"text":", OtcMarketsOrder and ","type":"text"},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/SpreadOrder","type":"reference","isActive":true},{"type":"text","text":" events."}],"type":"topic","url":"\/documentation\/dxfeedframework\/ordersource","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OrderSource","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"OrderSource","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"OrderSource"}],"title":"OrderSource","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXPriceType":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxpricetype","role":"symbol","title":"DXPriceType","kind":"symbol","abstract":[{"type":"text","text":"This "},{"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXPriceType","isActive":true},{"type":"text","text":" structure is created to circumvent the limitation that enums in Swift cannot contain stored properties."},{"type":"text","text":" "},{"type":"text","text":"The “Enums must not contain stored properties” error occurs when attempting to add a stored property to an enum. Instead, we use this structure to store data that we would like to include in the enum."}],"navigatorTitle":[{"text":"DXPriceType","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXPriceType","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DXPriceType","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Order":{"abstract":[{"text":"Order event is a snapshot for a full available market depth for a symbol.","type":"text"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Order","navigatorTitle":[{"text":"Order","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/order","title":"Order","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Order"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXCandleType":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxcandletype","role":"symbol","title":"DXCandleType","kind":"symbol","abstract":[{"type":"text","text":"This "},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXCandleType","isActive":true,"type":"reference"},{"type":"text","text":" structure is created to circumvent the limitation that enums in Swift cannot contain stored properties."},{"type":"text","text":" "},{"type":"text","text":"The “Enums must not contain stored properties” error occurs when attempting to add a stored property to an enum. Instead, we use this structure to store data that we would like to include in the enum."}],"navigatorTitle":[{"kind":"identifier","text":"DXCandleType"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXCandleType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DXCandleType","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/IndexedEventSubscriptionSymbol":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Non-generic version, for using with Symbol protocol without equatable T"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IndexedEventSubscriptionSymbol","kind":"identifier"}],"navigatorTitle":[{"text":"IndexedEventSubscriptionSymbol","kind":"identifier"}],"title":"IndexedEventSubscriptionSymbol","type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IndexedEventSubscriptionSymbol","url":"\/documentation\/dxfeedframework\/indexedeventsubscriptionsymbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Greeks":{"navigatorTitle":[{"kind":"identifier","text":"Greeks"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Greeks","kind":"identifier"}],"abstract":[{"text":"Greeks event is a snapshot of the option price, Black-Scholes volatility and greeks.","type":"text"}],"url":"\/documentation\/dxfeedframework\/greeks","title":"Greeks","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Greeks","kind":"symbol","type":"topic","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/IIndexedEvent":{"abstract":[{"type":"text","text":"Represents an indexed collection of up-to-date information about some"},{"type":"text","text":" "},{"text":"condition or state of an external entity that updates in real-time.","type":"text"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IIndexedEvent","navigatorTitle":[{"text":"IIndexedEvent","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/iindexedevent","title":"IIndexedEvent","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IIndexedEvent"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Direction":{"type":"topic","url":"\/documentation\/dxfeedframework\/direction","role":"symbol","kind":"symbol","title":"Direction","abstract":[{"text":"Direction of the price movement. For example tick direction for last trade price.","type":"text"}],"navigatorTitle":[{"text":"Direction","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Direction","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Direction"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/OrderBook":{"abstract":[],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OrderBook","title":"OrderBook","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OrderBook","kind":"identifier"}],"navigatorTitle":[{"text":"OrderBook","kind":"identifier"}],"url":"\/documentation\/dxfeedframework\/orderbook","type":"topic"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/CandlePeriod":{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandlePeriod","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CandlePeriod"}],"url":"\/documentation\/dxfeedframework\/candleperiod","title":"CandlePeriod","kind":"symbol","navigatorTitle":[{"text":"CandlePeriod","kind":"identifier"}],"abstract":[{"text":"Period attribute of ","type":"text"},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleSymbol","type":"reference","isActive":true},{"text":" defines aggregation period of the candles.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Aggregation period is defined as pair of a "},{"isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandlePeriod\/value","type":"reference"},{"text":" and ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandlePeriod\/type","type":"reference"},{"type":"text","text":"."}],"role":"symbol","type":"topic"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Quote":{"navigatorTitle":[{"text":"Quote","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Quote","kind":"identifier"}],"url":"\/documentation\/dxfeedframework\/quote","abstract":[{"text":"Quote event is a snapshot of the best bid and ask prices, and other fields that change with each quote.","type":"text"}],"title":"Quote","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Quote","kind":"symbol","type":"topic","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXDateOffset":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxdateoffset","role":"symbol","title":"DXDateOffset","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"DXDateOffset","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXDateOffset","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DXDateOffset","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/SnapshotDelegate":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Delegate for receiving snapshot and updates in snapshot"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SnapshotDelegate"}],"navigatorTitle":[{"text":"SnapshotDelegate","kind":"identifier"}],"title":"SnapshotDelegate","type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/SnapshotDelegate","url":"\/documentation\/dxfeedframework\/snapshotdelegate"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/QdsUtils":{"type":"topic","url":"\/documentation\/dxfeedframework\/qdsutils","role":"symbol","title":"QdsUtils","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"QdsUtils"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/QdsUtils","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"QdsUtils"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/CandleSession":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CandleSession"}],"url":"\/documentation\/dxfeedframework\/candlesession","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CandleSession","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Session attribute of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleSymbol","type":"reference"},{"type":"text","text":" defines trading that is used to build the candles."}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleSession","title":"CandleSession"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/CandleExchange":{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleExchange","abstract":[{"text":"Exchange attribute of ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleSymbol","isActive":true},{"type":"text","text":" defines exchange identifier where data is"},{"type":"text","text":" "},{"text":"taken from to build the candles.","type":"text"}],"url":"\/documentation\/dxfeedframework\/candleexchange","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CandleExchange"}],"title":"CandleExchange","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CandleExchange"}],"type":"topic","kind":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/StringUtil":{"type":"topic","url":"\/documentation\/dxfeedframework\/stringutil","role":"symbol","title":"StringUtil","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"StringUtil"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/StringUtil","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"StringUtil","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/TheoPrice":{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TheoPrice","navigatorTitle":[{"kind":"identifier","text":"TheoPrice"}],"role":"symbol","kind":"symbol","title":"TheoPrice","url":"\/documentation\/dxfeedframework\/theoprice","abstract":[{"type":"text","text":"Theo price is a snapshot of the theoretical option price computation that is"},{"type":"text","text":" "},{"type":"text","text":"periodically performed by http:\/\/www.devexperts.com\/en\/products\/price.html"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TheoPrice","kind":"identifier"}],"type":"topic"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Candle":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Candle","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dxfeedframework\/candle","navigatorTitle":[{"text":"Candle","kind":"identifier"}],"title":"Candle","abstract":[{"text":"Candle event with open, high, low, close prices and other information for a specific period.","type":"text"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Candle","kind":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/MarketEventSymbols":{"title":"MarketEventSymbols","navigatorTitle":[{"kind":"identifier","text":"MarketEventSymbols"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/MarketEventSymbols","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MarketEventSymbols","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Helper class to compose and parse symbols for market events.","type":"text"}],"url":"\/documentation\/dxfeedframework\/marketeventsymbols","type":"topic","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/WildcardSymbol":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WildcardSymbol","kind":"identifier"}],"navigatorTitle":[{"text":"WildcardSymbol","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents [wildcard] subscription to all events of the specific event type."}],"type":"topic","url":"\/documentation\/dxfeedframework\/wildcardsymbol","role":"symbol","title":"WildcardSymbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/WildcardSymbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXInstrumentProfileUpdateListener":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxinstrumentprofileupdatelistener","role":"symbol","title":"DXInstrumentProfileUpdateListener","kind":"symbol","abstract":[{"type":"text","text":"The listener delegate for receiving instrument profiles."}],"navigatorTitle":[{"kind":"identifier","text":"DXInstrumentProfileUpdateListener"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXInstrumentProfileUpdateListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DXInstrumentProfileUpdateListener"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/TimeAndSaleType":{"title":"TimeAndSaleType","navigatorTitle":[{"kind":"identifier","text":"TimeAndSaleType"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/timeandsaletype","abstract":[{"type":"text","text":"Type of a time and sale event."}],"type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TimeAndSaleType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimeAndSaleType","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/ITimeSeriesEvent":{"navigatorTitle":[{"kind":"identifier","text":"ITimeSeriesEvent"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ITimeSeriesEvent","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents time-series snapshots of some"},{"type":"text","text":" "},{"text":"process that is evolving in time or actual events in some external system","type":"text"},{"text":" ","type":"text"},{"text":"that have an associated time stamp and can be uniquely identified.","type":"text"}],"url":"\/documentation\/dxfeedframework\/itimeseriesevent","title":"ITimeSeriesEvent","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ITimeSeriesEvent","kind":"symbol","type":"topic","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXInstrumentProfileCollector":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxinstrumentprofilecollector","role":"symbol","title":"DXInstrumentProfileCollector","kind":"symbol","abstract":[{"type":"text","text":"Collects instrument profile updates and provides the live list of instrument profiles."}],"navigatorTitle":[{"text":"DXInstrumentProfileCollector","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXInstrumentProfileCollector","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DXInstrumentProfileCollector","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/ScheduleSessionType":{"type":"topic","url":"\/documentation\/dxfeedframework\/schedulesessiontype","role":"symbol","title":"ScheduleSessionType","kind":"symbol","abstract":[{"type":"text","text":"Defines type of a session - what kind of trading activity is allowed (if any),"},{"type":"text","text":" "},{"type":"text","text":"what rules are used, what impact on daily trading statistics it has, etc.."}],"navigatorTitle":[{"text":"ScheduleSessionType","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ScheduleSessionType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ScheduleSessionType","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/InstrumentProfileType":{"title":"InstrumentProfileType","navigatorTitle":[{"text":"InstrumentProfileType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/instrumentprofiletype","abstract":[{"type":"text","text":"Defines standard types of "},{"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/InstrumentProfile","isActive":true},{"type":"text","text":"."}],"type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/InstrumentProfileType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InstrumentProfileType"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/MarketEventConst":{"type":"topic","url":"\/documentation\/dxfeedframework\/marketeventconst","role":"symbol","title":"MarketEventConst","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"MarketEventConst","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/MarketEventConst","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MarketEventConst"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/TimeUtil":{"type":"topic","url":"\/documentation\/dxfeedframework\/timeutil","role":"symbol","title":"TimeUtil","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"TimeUtil","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TimeUtil","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TimeUtil","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXSchedule":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxschedule","role":"symbol","title":"DXSchedule","kind":"symbol","abstract":[{"type":"text","text":"Schedule class provides API to retrieve and explore trading schedules of different exchanges"},{"text":" ","type":"text"},{"text":"and different classes of financial instruments.","type":"text"}],"navigatorTitle":[{"text":"DXSchedule","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXSchedule","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DXSchedule","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXFeedTimeSeriesSubscription":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxfeedtimeseriessubscription","role":"symbol","title":"DXFeedTimeSeriesSubscription","kind":"symbol","abstract":[{"type":"text","text":"Extends "},{"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXFeedSubscription","isActive":true},{"type":"text","text":" to conveniently subscribe to time-series of"},{"type":"text","text":" "},{"type":"text","text":"events for a set of symbols and event types."}],"navigatorTitle":[{"text":"DXFeedTimeSeriesSubscription","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXFeedTimeSeriesSubscription","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DXFeedTimeSeriesSubscription","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXEndpoint":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxendpoint","role":"symbol","title":"DXEndpoint","kind":"symbol","abstract":[{"text":"Manages network connections to ","type":"text"},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXFeed","type":"reference","isActive":true},{"text":" or ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXPublisher","isActive":true}],"navigatorTitle":[{"text":"DXEndpoint","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXEndpoint","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DXEndpoint","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/AnalyticOrder":{"navigatorTitle":[{"text":"AnalyticOrder","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnalyticOrder"}],"abstract":[{"text":"Represents an extension of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Order"},{"text":" introducing analytics information,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"e.g. adding to this order iceberg related information "},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/AnalyticOrder\/icebergPeakSize","type":"reference","isActive":true},{"text":", ","type":"text"},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/AnalyticOrder\/icebergHiddenSize","type":"reference","isActive":true},{"type":"text","text":", "},{"isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/AnalyticOrder\/icebergExecutedSize","type":"reference"}],"url":"\/documentation\/dxfeedframework\/analyticorder","title":"AnalyticOrder","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/AnalyticOrder","kind":"symbol","type":"topic","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/MarketDepthListener":{"type":"topic","url":"\/documentation\/dxfeedframework\/marketdepthlistener","role":"symbol","title":"MarketDepthListener","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"MarketDepthListener","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/MarketDepthListener","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MarketDepthListener"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Underlying":{"kind":"symbol","url":"\/documentation\/dxfeedframework\/underlying","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Underlying","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Underlying","navigatorTitle":[{"kind":"identifier","text":"Underlying"}],"type":"topic","role":"symbol","title":"Underlying","abstract":[{"type":"text","text":"Underlying event is a snapshot of computed values that are available for an option underlying"},{"text":" ","type":"text"},{"text":"symbol based on the option prices on the market.","type":"text"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/CandleAlignment":{"type":"topic","url":"\/documentation\/dxfeedframework\/candlealignment","role":"symbol","title":"CandleAlignment","kind":"symbol","abstract":[{"type":"text","text":"Candle alignment attribute of "},{"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleSymbol","isActive":true},{"text":" defines how candle are aligned with respect to time.","type":"text"}],"navigatorTitle":[{"text":"CandleAlignment","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleAlignment","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CandleAlignment","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/OrderBase":{"navigatorTitle":[{"text":"OrderBase","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"OrderBase","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dxfeedframework\/orderbase","title":"OrderBase","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OrderBase","kind":"symbol","type":"topic","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/CandlePriceLevel":{"type":"topic","url":"\/documentation\/dxfeedframework\/candlepricelevel","navigatorTitle":[{"text":"CandlePriceLevel","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandlePriceLevel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CandlePriceLevel"}],"title":"CandlePriceLevel","abstract":[{"text":"Candle price level attribute of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleSymbol","type":"reference"},{"type":"text","text":" defines how candles shall be aggregated in respect to"},{"type":"text","text":" "},{"text":"price interval. The negative or infinite values of price interval are treated as exceptional.","type":"text"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/CandlePrice":{"url":"\/documentation\/dxfeedframework\/candleprice","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"CandlePrice","kind":"identifier"}],"abstract":[{"text":"Price type attribute of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleSymbol"},{"type":"text","text":" defines price that is used to build the candles."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CandlePrice","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandlePrice","title":"CandlePrice"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/ScheduleDay":{"abstract":[{"type":"text","text":"Day represents a continuous period of time approximately 24 hours long."}],"navigatorTitle":[{"text":"ScheduleDay","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ScheduleDay","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ScheduleDay","kind":"identifier"}],"url":"\/documentation\/dxfeedframework\/scheduleday","kind":"symbol","title":"ScheduleDay","type":"topic","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXFeedSubscription":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DXFeedSubscription","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dxfeedframework\/dxfeedsubscription","navigatorTitle":[{"text":"DXFeedSubscription","kind":"identifier"}],"title":"DXFeedSubscription","abstract":[{"text":"Subscription for a set of symbols and event types.","type":"text"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXFeedSubscription","kind":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/CandleType":{"title":"CandleType","navigatorTitle":[{"text":"CandleType","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/candletype","abstract":[],"type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CandleType","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Profile":{"navigatorTitle":[{"text":"Profile","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Profile","kind":"identifier"}],"url":"\/documentation\/dxfeedframework\/profile","abstract":[{"type":"text","text":"Profile information snapshot that contains security instrument description."}],"title":"Profile","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Profile","kind":"symbol","type":"topic","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Long":{"title":"Long","navigatorTitle":[{"text":"Long","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Long","url":"\/documentation\/dxfeedframework\/long","abstract":[],"role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Long"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/ScopingFunctionSupported":{"abstract":[],"navigatorTitle":[{"text":"ScopingFunctionSupported","kind":"identifier"}],"title":"ScopingFunctionSupported","url":"\/documentation\/dxfeedframework\/scopingfunctionsupported","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScopingFunctionSupported"}],"kind":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ScopingFunctionSupported"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Swift":{"role":"collection","url":"\/documentation\/dxfeedframework\/swift","abstract":[],"title":"Swift","type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Swift","kind":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/CandlePeriod/value":{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandlePeriod\/value","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"value"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/dxfeedframework\/candleperiod\/value","title":"value","kind":"symbol","abstract":[{"type":"text","text":"Gets aggregation period value."},{"text":" ","type":"text"},{"text":"For example, the value of 5 with","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the candle type of "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleType\/minute"},{"text":" represents 5 minute","type":"text"},{"type":"text","text":" "},{"text":"aggregation period.","type":"text"}],"role":"symbol","type":"topic"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/TradeETH":{"navigatorTitle":[{"text":"TradeETH","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TradeETH"}],"url":"\/documentation\/dxfeedframework\/tradeeth","abstract":[{"text":"TradeETH event is a snapshot of the price and size of the last trade during","type":"text"},{"text":" ","type":"text"},{"text":"extended trading hours and the extended trading hours day volume and day turnover.","type":"text"}],"title":"TradeETH","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TradeETH","kind":"symbol","type":"topic","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/AnalyticOrder/icebergPeakSize":{"abstract":[{"type":"text","text":"Gets or sets iceberg peak size of this analytic order."}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/AnalyticOrder\/icebergPeakSize","kind":"symbol","url":"\/documentation\/dxfeedframework\/analyticorder\/icebergpeaksize","title":"icebergPeakSize","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"icebergPeakSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Series":{"abstract":[{"type":"text","text":"Series event is a snapshot of computed values that are available for all option series for"},{"type":"text","text":" "},{"text":"a given underlying symbol based on the option prices on the market.","type":"text"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Series","navigatorTitle":[{"kind":"identifier","text":"Series"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/series","title":"Series","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Series","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXOtcMarketsPriceType":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxotcmarketspricetype","role":"symbol","title":"DXOtcMarketsPriceType","kind":"symbol","abstract":[{"type":"text","text":"This "},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXOtcMarketsPriceType","type":"reference","isActive":true},{"type":"text","text":" structure is created to circumvent the limitation that enums in Swift cannot contain stored properties."},{"type":"text","text":" "},{"text":"The “Enums must not contain stored properties” error occurs when attempting to add a stored property to an enum. Instead, we use this structure to store data that we would like to include in the enum.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DXOtcMarketsPriceType"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXOtcMarketsPriceType","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DXOtcMarketsPriceType","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Summary":{"type":"topic","url":"\/documentation\/dxfeedframework\/summary","role":"symbol","kind":"symbol","title":"Summary","abstract":[{"type":"text","text":"Summary information snapshot about the trading session including session highs, lows, etc."}],"navigatorTitle":[{"text":"Summary","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Summary","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Summary"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/PriceType":{"navigatorTitle":[{"kind":"identifier","text":"PriceType"}],"title":"PriceType","url":"\/documentation\/dxfeedframework\/pricetype","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/PriceType","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PriceType"}],"abstract":[],"kind":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Role":{"type":"topic","url":"\/documentation\/dxfeedframework\/role","role":"symbol","title":"Role","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Role"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Role","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Role"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXEndpointState":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxendpointstate","role":"symbol","title":"DXEndpointState","kind":"symbol","abstract":[{"type":"text","text":"A list of endpoint states."}],"navigatorTitle":[{"text":"DXEndpointState","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXEndpointState","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DXEndpointState"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/CandlePeriod/type":{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandlePeriod\/type","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CandleType","kind":"typeIdentifier","preciseIdentifier":"s:15DXFeedFramework10CandleTypeO"}],"kind":"symbol","type":"topic","role":"symbol","title":"type","url":"\/documentation\/dxfeedframework\/candleperiod\/type","abstract":[{"type":"text","text":"Gets aggregation period type."}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/GraalException":{"navigatorTitle":[{"text":"GraalException","kind":"identifier"}],"title":"GraalException","url":"\/documentation\/dxfeedframework\/graalexception","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/GraalException","role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GraalException","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents errors that occur when calling graal function."}],"kind":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/ShortSaleRestriction":{"type":"topic","kind":"symbol","abstract":[{"text":"Short sale restriction on an instrument.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ShortSaleRestriction"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ShortSaleRestriction","kind":"identifier"}],"url":"\/documentation\/dxfeedframework\/shortsalerestriction","role":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ShortSaleRestriction","title":"ShortSaleRestriction"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/OptionChainsBuilder":{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OptionChainsBuilder","type":"topic","navigatorTitle":[{"text":"OptionChainsBuilder","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"OptionChainsBuilder","kind":"identifier"}],"abstract":[{"type":"text","text":"Builder class for a set of option chains grouped by product or underlying symbol."}],"url":"\/documentation\/dxfeedframework\/optionchainsbuilder","role":"symbol","title":"OptionChainsBuilder"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/stringReference(_:)":{"type":"topic","url":"\/documentation\/dxfeedframework\/stringreference(_:)","role":"symbol","title":"stringReference(_:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/stringReference(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stringReference"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s9AnyObjecta","text":"AnyObject"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/InstrumentProfile":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"InstrumentProfile","kind":"identifier"}],"navigatorTitle":[{"text":"InstrumentProfile","kind":"identifier"}],"abstract":[{"text":"Represents basic profile information about market instrument.","type":"text"}],"type":"topic","url":"\/documentation\/dxfeedframework\/instrumentprofile","role":"symbol","title":"InstrumentProfile","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/InstrumentProfile"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DxFeedFrameworkVersionNumber":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxfeedframeworkversionnumber","role":"symbol","title":"DxFeedFrameworkVersionNumber","kind":"symbol","abstract":[{"type":"text","text":"Project version number for DxFeedFramework."}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DxFeedFrameworkVersionNumber","fragments":[{"text":"DxFeedFrameworkVersionNumber","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/MarketEvent":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MarketEvent"}],"type":"topic","url":"\/documentation\/dxfeedframework\/marketevent","navigatorTitle":[{"kind":"identifier","text":"MarketEvent"}],"title":"MarketEvent","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/MarketEvent","abstract":[{"text":"Protocol for all market events.","type":"text"},{"text":" ","type":"text"},{"text":"All market events are objects that","type":"text"},{"text":" ","type":"text"},{"text":"extend this class. Market event classes are simple beans with setter and getter methods for their","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"properties and minimal business logic. All market events have "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/MarketEvent\/type-swift.property"},{"text":" ","type":"text"},{"type":"text","text":"property that is defined by this class."}],"role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/IndexedEventSource":{"type":"topic","url":"\/documentation\/dxfeedframework\/indexedeventsource","role":"symbol","title":"IndexedEventSource","kind":"symbol","abstract":[{"type":"text","text":"Source identifier for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IIndexedEvent"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"IndexedEventSource"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IndexedEventSource","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IndexedEventSource","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXInstrumentProfileConnectionListener":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxinstrumentprofileconnectionlistener","role":"symbol","title":"DXInstrumentProfileConnectionListener","kind":"symbol","abstract":[{"type":"text","text":"Notifies a change in the state of this connection."}],"navigatorTitle":[{"kind":"identifier","text":"DXInstrumentProfileConnectionListener"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXInstrumentProfileConnectionListener","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DXInstrumentProfileConnectionListener"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/ILastingEvent":{"type":"topic","url":"\/documentation\/dxfeedframework\/ilastingevent","role":"symbol","title":"ILastingEvent","kind":"symbol","abstract":[{"type":"text","text":"Represents up-to-date information about some"},{"text":" ","type":"text"},{"type":"text","text":"condition or state of an external entity that updates in real-time."}],"navigatorTitle":[{"text":"ILastingEvent","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ILastingEvent","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ILastingEvent","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Scope":{"type":"topic","url":"\/documentation\/dxfeedframework\/scope","role":"symbol","title":"Scope","kind":"symbol","abstract":[{"type":"text","text":"Scope of an order."}],"navigatorTitle":[{"text":"Scope","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Scope","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Scope"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Promise":{"kind":"symbol","url":"\/documentation\/dxfeedframework\/promise","navigatorTitle":[{"text":"Promise","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Promise","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Promise","kind":"identifier"}],"title":"Promise","type":"topic","abstract":[{"type":"text","text":"Result of a computation that will be completed normally or exceptionally in the future."},{"type":"text","text":" "},{"type":"text","text":"This class is designed to represent a promise to deliver certain result."}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/NativeInstrumentProfileCollector":{"title":"NativeInstrumentProfileCollector","navigatorTitle":[{"kind":"identifier","text":"NativeInstrumentProfileCollector"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/nativeinstrumentprofilecollector","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/NativeInstrumentProfileCollector","type":"topic","abstract":[{"type":"text","text":"Native wrapper over the Java com.dxfeed.ipf.live.InstrumentProfileCollector class."},{"text":" ","type":"text"},{"text":"The location of the imported functions is in the header files “dxfg_ipf.h”.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NativeInstrumentProfileCollector","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Symbol":{"title":"Symbol","navigatorTitle":[{"text":"Symbol","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Symbol","url":"\/documentation\/dxfeedframework\/symbol","abstract":[{"text":"Protocol for implement your custom symbol","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Symbol","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/TradeBase":{"navigatorTitle":[{"kind":"identifier","text":"TradeBase"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TradeBase"}],"abstract":[{"text":"Base class for common fields of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Trade"},{"text":" and ","type":"text"},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TradeETH","isActive":true,"type":"reference"},{"type":"text","text":" events."}],"url":"\/documentation\/dxfeedframework\/tradebase","title":"TradeBase","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TradeBase","kind":"symbol","type":"topic","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXTimeZone":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxtimezone","role":"symbol","title":"DXTimeZone","kind":"symbol","abstract":[{"type":"text","text":"It is just wrapper aroung Java TimeZone"}],"navigatorTitle":[{"text":"DXTimeZone","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXTimeZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DXTimeZone","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXEventListener":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxeventlistener","role":"symbol","kind":"symbol","title":"DXEventListener","abstract":[{"type":"text","text":"The listener delegate for receiving events."}],"navigatorTitle":[{"kind":"identifier","text":"DXEventListener"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXEventListener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DXEventListener","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/MarketDepthModel":{"title":"MarketDepthModel","navigatorTitle":[{"text":"MarketDepthModel","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/marketdepthmodel","abstract":[],"type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/MarketDepthModel","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MarketDepthModel"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/TxMode":{"title":"TxMode","navigatorTitle":[{"text":"TxMode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/txmode","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TxMode","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TxMode","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/SpreadOrder":{"navigatorTitle":[{"text":"SpreadOrder","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SpreadOrder","kind":"identifier"}],"abstract":[{"text":"Spread order event is a snapshot for a full available market depth for all spreads","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"on a given underlying symbol."}],"url":"\/documentation\/dxfeedframework\/spreadorder","title":"SpreadOrder","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/SpreadOrder","kind":"symbol","type":"topic","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/TimeAndSale":{"navigatorTitle":[{"text":"TimeAndSale","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TimeAndSale","kind":"identifier"}],"url":"\/documentation\/dxfeedframework\/timeandsale","abstract":[{"type":"text","text":"Time and Sale represents a trade or other market event with price, like market open\/close price, etc."}],"title":"TimeAndSale","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TimeAndSale","kind":"symbol","type":"topic","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/OptionSeries":{"title":"OptionSeries","kind":"symbol","abstract":[{"type":"text","text":"Series of call and put options with different strike sharing the same attributes of"},{"text":" ","type":"text"},{"type":"text","text":"expiration, last trading day, spc, multiplies, etc."}],"navigatorTitle":[{"text":"OptionSeries","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OptionSeries"}],"url":"\/documentation\/dxfeedframework\/optionseries","role":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OptionSeries","type":"topic"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/TimeSeriesSubscriptionSymbol":{"title":"TimeSeriesSubscriptionSymbol","navigatorTitle":[{"text":"TimeSeriesSubscriptionSymbol","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/timeseriessubscriptionsymbol","abstract":[{"type":"text","text":"Represents subscription to time-series of events."}],"type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TimeSeriesSubscriptionSymbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TimeSeriesSubscriptionSymbol","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DayFilter":{"url":"\/documentation\/dxfeedframework\/dayfilter","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DayFilter","kind":"identifier"}],"title":"DayFilter","navigatorTitle":[{"text":"DayFilter","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DayFilter","abstract":[]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/SessionFilter":{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/SessionFilter","kind":"symbol","title":"SessionFilter","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SessionFilter","kind":"identifier"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"SessionFilter","kind":"identifier"}],"url":"\/documentation\/dxfeedframework\/sessionfilter"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DxFeedFrameworkVersionString":{"title":"DxFeedFrameworkVersionString","kind":"symbol","url":"\/documentation\/dxfeedframework\/dxfeedframeworkversionstring","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DxFeedFrameworkVersionString","type":"topic","abstract":[{"text":"Project version string for DxFeedFramework.","type":"text"}],"role":"symbol","fragments":[{"kind":"identifier","text":"DxFeedFrameworkVersionString"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework":{"url":"\/documentation\/dxfeedframework","kind":"symbol","role":"collection","abstract":[],"title":"DXFeedFramework","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework","type":"topic"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXCandleAlignment":{"title":"DXCandleAlignment","navigatorTitle":[{"kind":"identifier","text":"DXCandleAlignment"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/dxcandlealignment","abstract":[{"type":"text","text":"This "},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXCandleAlignment","isActive":true,"type":"reference"},{"text":" structure is created to circumvent the limitation that enums in Swift cannot contain stored properties.","type":"text"},{"type":"text","text":" "},{"text":"The “Enums must not contain stored properties” error occurs when attempting to add a stored property to an enum. Instead, we use this structure to store data that we would like to include in the enum.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXCandleAlignment","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DXCandleAlignment","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/SymbolParser":{"title":"SymbolParser","navigatorTitle":[{"text":"SymbolParser","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/symbolparser","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/SymbolParser","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SymbolParser"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Foundation":{"type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Foundation","kind":"symbol","title":"Foundation","abstract":[],"url":"\/documentation\/dxfeedframework\/foundation","role":"collection"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXProfileIterator":{"title":"DXProfileIterator","navigatorTitle":[{"text":"DXProfileIterator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/dxprofileiterator","abstract":[{"type":"text","text":"An iterator over a "},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/InstrumentProfile","type":"reference","isActive":true},{"type":"text","text":" collection."}],"type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXProfileIterator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DXProfileIterator","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/IObservableSubscription":{"title":"IObservableSubscription","navigatorTitle":[{"kind":"identifier","text":"IObservableSubscription"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/iobservablesubscription","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IObservableSubscription","type":"topic","abstract":[{"text":"Observable set of subscription symbols for the specific event type.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IObservableSubscription","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Trade":{"kind":"symbol","url":"\/documentation\/dxfeedframework\/trade","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Trade","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Trade","navigatorTitle":[{"text":"Trade","kind":"identifier"}],"type":"topic","role":"symbol","title":"Trade","abstract":[{"text":"Trade event is a snapshot of the price and size of the last trade during regular trading hours","type":"text"},{"type":"text","text":" "},{"text":"and an overall day volume and day turnover.","type":"text"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/InstrumentProfileField":{"url":"\/documentation\/dxfeedframework\/instrumentprofilefield","title":"InstrumentProfileField","kind":"symbol","abstract":[{"text":"Defines standard fields of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/InstrumentProfile"},{"text":" and provides data access methods.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"InstrumentProfileField","kind":"identifier"}],"navigatorTitle":[{"text":"InstrumentProfileField","kind":"identifier"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/InstrumentProfileField"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/MarketEvent/type-swift.property":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:15DXFeedFramework9EventCodeO","text":"EventCode","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/dxfeedframework\/marketevent\/type-swift.property","title":"type","abstract":[],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/MarketEvent\/type-swift.property","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/CandleSymbol":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CandleSymbol","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dxfeedframework\/candlesymbol","navigatorTitle":[{"kind":"identifier","text":"CandleSymbol"}],"title":"CandleSymbol","abstract":[{"text":"Symbol that should be used with","type":"text"},{"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXFeedSubscription","isActive":true},{"text":" class","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to subscribe for"},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Candle","isActive":true,"type":"reference"},{"text":" events.","type":"text"},{"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXFeedSubscription","isActive":true},{"type":"text","text":" also accepts a string"},{"type":"text","text":" "},{"type":"text","text":"representation of the candle symbol for subscription."}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/CandleSymbol","kind":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/ScopeExt":{"title":"ScopeExt","navigatorTitle":[{"text":"ScopeExt","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/scopeext","abstract":[{"type":"text","text":"Class extension for "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ScopeExt"},{"type":"text","text":" enum."}],"type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ScopeExt","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ScopeExt"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/GenericIndexedEventSubscriptionSymbol":{"title":"GenericIndexedEventSubscriptionSymbol","navigatorTitle":[{"text":"GenericIndexedEventSubscriptionSymbol","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/genericindexedeventsubscriptionsymbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/GenericIndexedEventSubscriptionSymbol","type":"topic","abstract":[{"type":"text","text":"Represents subscription to a specific source of indexed events."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GenericIndexedEventSubscriptionSymbol","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/OptionChain":{"title":"OptionChain","navigatorTitle":[{"text":"OptionChain","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/optionchain","abstract":[{"type":"text","text":"Set of option series for a single product or underlying symbol."}],"type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/OptionChain","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"OptionChain"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXFeed":{"title":"DXFeed","navigatorTitle":[{"kind":"identifier","text":"DXFeed"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXFeed","url":"\/documentation\/dxfeedframework\/dxfeed","abstract":[{"type":"text","text":"Main entry class for dxFeed API."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DXFeed","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXTimeFormat":{"navigatorTitle":[{"text":"DXTimeFormat","kind":"identifier"}],"title":"DXTimeFormat","url":"\/documentation\/dxfeedframework\/dxtimeformat","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXTimeFormat","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DXTimeFormat"}],"abstract":[{"type":"text","text":"Utility class for parsing and formatting dates and times in ISO-compatible format."}],"kind":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/SnapshotProcessor":{"abstract":[{"text":"The SnapshotProcessor class is designed to handle candles and provide either a snapshot of the data or updates within an existing snapshot, depending on the specified flags.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"SnapshotProcessor","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SnapshotProcessor"}],"url":"\/documentation\/dxfeedframework\/snapshotprocessor","role":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/SnapshotProcessor","title":"SnapshotProcessor"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/ScheduleSession":{"title":"ScheduleSession","navigatorTitle":[{"kind":"identifier","text":"ScheduleSession"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/schedulesession","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/ScheduleSession","type":"topic","abstract":[{"type":"text","text":"Session represents a continuous period of time during which apply same rules regarding trading activity."},{"type":"text","text":" "},{"text":"For example, regular trading session is a period of time consisting of one day of business activities","type":"text"},{"type":"text","text":" "},{"text":"in a financial market, from the opening bell to the closing bell, when regular trading occurs.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ScheduleSession"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/IcebergTypeExt":{"title":"IcebergTypeExt","navigatorTitle":[{"kind":"identifier","text":"IcebergTypeExt"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/icebergtypeext","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IcebergTypeExt","type":"topic","abstract":[{"type":"text","text":"Class extension for  "},{"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IcebergType","isActive":true,"type":"reference"},{"type":"text","text":" enum."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IcebergTypeExt","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/EventCode":{"url":"\/documentation\/dxfeedframework\/eventcode","type":"topic","title":"EventCode","kind":"symbol","abstract":[{"type":"text","text":"A list of all events, that can be passed to\/from native code, represented as a numeric code."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventCode"}],"role":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/EventCode","navigatorTitle":[{"kind":"identifier","text":"EventCode"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXInstrumentProfileReader":{"abstract":[{"text":"Reads instrument profiles from the stream using Instrument Profile Format (IPF).","type":"text"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXInstrumentProfileReader","navigatorTitle":[{"text":"DXInstrumentProfileReader","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dxfeedframework\/dxinstrumentprofilereader","title":"DXInstrumentProfileReader","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DXInstrumentProfileReader","kind":"identifier"}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/Builder":{"type":"topic","kind":"symbol","abstract":[{"text":"Builder class for ","type":"text"},{"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXEndpoint","isActive":true},{"text":" that supports additional configuration properties.","type":"text"}],"navigatorTitle":[{"text":"Builder","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Builder"}],"url":"\/documentation\/dxfeedframework\/builder","role":"symbol","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/Builder","title":"Builder"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/IcebergType":{"title":"IcebergType","abstract":[{"text":"Type of an iceberg order.","type":"text"}],"type":"topic","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/IcebergType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IcebergType"}],"url":"\/documentation\/dxfeedframework\/icebergtype","navigatorTitle":[{"kind":"identifier","text":"IcebergType"}],"kind":"symbol","role":"symbol"},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/TradingStatus":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TradingStatus"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TradingStatus"}],"url":"\/documentation\/dxfeedframework\/tradingstatus","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/TradingStatus","title":"TradingStatus","kind":"symbol","abstract":[{"type":"text","text":"Trading status of an instrument."}]},"doc://com.dxfeed.DXFeedFramework/documentation/DXFeedFramework/DXPublisher":{"type":"topic","url":"\/documentation\/dxfeedframework\/dxpublisher","role":"symbol","title":"DXPublisher","kind":"symbol","abstract":[{"type":"text","text":"Provides API for publishing of events to local or remote  "},{"isActive":true,"type":"reference","identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXFeed"}],"navigatorTitle":[{"kind":"identifier","text":"DXPublisher"}],"identifier":"doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DXPublisher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DXPublisher"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DxFeedFrameworkVersionNumber","doc:\/\/com.dxfeed.DXFeedFramework\/documentation\/DXFeedFramework\/DxFeedFrameworkVersionString"],"title":"Variables"}]},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"}]}]}