name: "CI"

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
    contents: write

jobs:
  build_and_upload_docs:
    if: (startsWith(github.event.ref, 'refs/tags/') && endsWith(github.event.ref, 'build'))
    name: Build & Upload Docs
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch dep
        run: gradle fetchDependencies

      - name: Create HTML Docs
        run: ./build_doc.sh ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
        shell: sh

      - name: Upload Doc
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: help
          commit_message: 'deploy: ${{ github.ref_name }}'
          allow_empty_commit: true
